In [107]:
from dqt import DBUtils, get_fut_min, get_fut_taq
import pandas as pd

In [108]:
dbu = DBUtils()
varieties = ['SP', 'EG']#CY，SN，FU，'SC'
varieties = pd.Series(varieties)

all_varieties = ['A', 'AG', 'AL', 'AU', 'AP', 'BU', 'B', 'C', 'CF', 'CJ', 'CS', 'CU', 'CY', 'EG', 'FG', 'HC', 'I', 'J',
                'JD', 'JM', 'L', 'M', 'MA', 'NI', 'NR', 'OI', 'P', 'PB', 'PP', 'RB', 'RM', 'RU', 'SC', 'SP', 'SR', 'T',
                'TA', 'TF', 'TS', 'UR', 'V', 'Y', 'ZC', 'ZN']

In [119]:
c = list ()
for i,variety in varieties.iteritems():
    print('variety: ', variety)
    df = dbu.get_main_daily(variety=[variety], start_date='2014-01-01')
    summary_df = df.groupby('symbol').agg({'date': ['first', 'last']})
    print('summary_df: ', summary_df)
    sleep(1000)
    a = list()
    b = list()
    for i, contract in summary_df.iterrows():
        min_df = get_fut_min(contract.name, str(contract[('date', 'first')].date()), str(contract[('date', 'last')].date()))
        taq_df = get_fut_taq(contract.name, str(contract[('date', 'first')].date()), str(contract[('date', 'last')].date()))
        print(taq_df.groupby(taq_df.index))
        a.append(min_df.groupby('trading_date').count()['datetime'])
        b.append(taq_df.groupby(taq_df.index).count()['datetime'])
        del min_df
        del taq_df

    merge_a = pd.concat(a)
    merge_b = pd.concat(b)
    del a  
    del b

    c.append({'期货':variety,'taq数据少':merge_b[merge_b == merge_b.describe()['min']], '日数据存在而taq数据缺少':pd.Index(df['date']).difference(merge_b.index),'大于30000条记录':merge_b[merge_b>30000]})

c = pd.DataFrame(c)

variety:  SP
summary_df:               date
            first       last
symbol
SP1906 2018-11-27 2019-04-29
SP1909 2019-04-30 2019-08-07
SP2001 2019-08-08 2019-08-30
variety:  EG
summary_df:               date
            first       last
symbol
EG1906 2018-12-10 2019-04-26
EG1909 2019-04-29 2019-07-31
EG2001 2019-08-01 2019-09-03

In [105]:
print(c)

                                              taq数据少  \
0  trading_date
2019-04-30    11015
Name: datetim...
1  trading_date
2019-02-18    5569
Name: datetime...

                                          大于30000条记录  \
0  trading_date
2018-11-29    37984
2018-11-30   ...
1  trading_date
2019-04-04    32846
2019-04-16   ...

                                       日数据存在而taq数据缺少  期货
0  DatetimeIndex([], dtype='datetime64[ns]', name...  SP
1  DatetimeIndex(['2019-09-02'], dtype='datetime6...  EG

In [98]:
c.to_csv("futures.csv")

In [118]:
symbol = 'SP1909'
taq_df = get_fut_taq(symbol, start_date='2010-01-01')
print(taq_df)

                            datetime    last  volume   turnover     oi  \
trading_date
2018-11-27   2018-11-27 07:05:02.000  5980.0       0          0      0
2018-11-27   2018-11-27 08:59:00.500  5900.0      86    5074000     86
2018-11-27   2018-11-27 09:00:00.500  5900.0      92    5428000     92
2018-11-27   2018-11-27 09:00:01.000  5860.0     100    5896000    100
2018-11-27   2018-11-27 09:00:01.500  5806.0     106    6246480    106
2018-11-27   2018-11-27 09:00:02.000  5856.0     114    6714800    114
2018-11-27   2018-11-27 09:00:02.500  5854.0     124    7298760    124
2018-11-27   2018-11-27 09:00:03.000  5854.0     128    7532920    128
2018-11-27   2018-11-27 09:00:03.500  5854.0     152    8929960    138
2018-11-27   2018-11-27 09:00:04.000  5828.0     160    9395320    146
2018-11-27   2018-11-27 09:00:04.500  5850.0     164    9628880    150
2018-11-27   2018-11-27 09:00:05.000  5806.0     168    9862080    152
2018-11-27   2018-11-27 09:00:05.500  5854.0     170    9979160    152
2018-11-27   2018-11-27 09:00:06.000  5814.0     172   10095440    150
2018-11-27   2018-11-27 09:00:06.500  5814.0     172   10095440    150
2018-11-27   2018-11-27 09:00:07.000  5814.0     172   10095440    150
2018-11-27   2018-11-27 09:00:07.500  5814.0     172   10095440    150
2018-11-27   2018-11-27 09:00:08.000  5818.0     174   10211800    150
2018-11-27   2018-11-27 09:00:08.500  5816.0     178   10444440    152
2018-11-27   2018-11-27 09:00:09.000  5818.0     182   10677160    156
2018-11-27   2018-11-27 09:00:09.500  5818.0     184   10793520    156
2018-11-27   2018-11-27 09:00:10.000  5822.0     194   11376360    150
2018-11-27   2018-11-27 09:00:10.500  5818.0     198   11609080    154
2018-11-27   2018-11-27 09:00:11.000  5820.0     200   11725480    154
2018-11-27   2018-11-27 09:00:11.500  5820.0     200   11725480    154
2018-11-27   2018-11-27 09:00:12.000  5820.0     200   11725480    154
2018-11-27   2018-11-27 09:00:12.500  5814.0     202   11841760    156
2018-11-27   2018-11-27 09:00:13.000  5814.0     204   11958040    158
2018-11-27   2018-11-27 09:00:13.500  5814.0     204   11958040    158
2018-11-27   2018-11-27 09:00:14.000  5816.0     206   12074360    160
...                              ...     ...     ...        ...    ...
2019-08-30   2019-08-30 14:58:43.000  4558.0   11762  539688680  12578
2019-08-30   2019-08-30 14:58:45.000  4558.0   11782  540600280  12578
2019-08-30   2019-08-30 14:58:45.500  4558.0   11782  540600280  12578
2019-08-30   2019-08-30 14:58:48.000  4558.0   11782  540600280  12578
2019-08-30   2019-08-30 14:59:01.500  4558.0   11782  540600280  12578
2019-08-30   2019-08-30 14:59:02.000  4560.0   11788  540873880  12578
2019-08-30   2019-08-30 14:59:02.500  4560.0   11788  540873880  12578
2019-08-30   2019-08-30 14:59:10.000  4556.0   11794  541147280  12574
2019-08-30   2019-08-30 14:59:10.500  4556.0   11808  541785120  12574
2019-08-30   2019-08-30 14:59:11.000  4556.0   11808  541785120  12574
2019-08-30   2019-08-30 14:59:11.500  4556.0   11808  541785120  12574
2019-08-30   2019-08-30 14:59:12.000  4556.0   11808  541785120  12574
2019-08-30   2019-08-30 14:59:12.500  4556.0   11808  541785120  12574
2019-08-30   2019-08-30 14:59:13.000  4556.0   11808  541785120  12574
2019-08-30   2019-08-30 14:59:19.000  4556.0   11808  541785120  12574
2019-08-30   2019-08-30 14:59:24.000  4556.0   11808  541785120  12574
2019-08-30   2019-08-30 14:59:29.000  4556.0   11808  541785120  12574
2019-08-30   2019-08-30 14:59:30.500  4556.0   11808  541785120  12574
2019-08-30   2019-08-30 14:59:32.500  4558.0   11828  542696720  12574
2019-08-30   2019-08-30 14:59:33.000  4558.0   11830  542787880  12574
2019-08-30   2019-08-30 14:59:34.000  4558.0   11830  542787880  12574
2019-08-30   2019-08-30 14:59:41.000  4558.0   11830  542787880  12574
2019-08-30   2019-08-30 14:59:45.500  4558.0   11830  542787880  12574
2019-08-30   2019-08-30 14:59:47.500  4558.0   11830  542787880  12574
2019-08-30   2019-08-30 14:59:54.500  4558.0   11830  542787880  12574
2019-08-30   2019-08-30 14:59:55.500  4560.0   11834  542970280  12570
2019-08-30   2019-08-30 14:59:56.000  4560.0   11834  542970280  12570
2019-08-30   2019-08-30 14:59:57.500  4560.0   11834  542970280  12570
2019-08-30   2019-08-30 15:00:00.500  4560.0   11834  542970280  12570
2019-08-30   2019-08-30 15:20:15.000  4560.0   11834  542970280  12570

                  a1  a1v      b1  b1v  symbol
trading_date
2018-11-27       0.0    0     0.0    0  SP1909
2018-11-27    5900.0  302  5800.0    1  SP1909
2018-11-27    5860.0   97  5802.0    2  SP1909
2018-11-27    5858.0   12  5802.0    2  SP1909
2018-11-27    5856.0   14  5806.0    1  SP1909
2018-11-27    5854.0    4  5828.0    1  SP1909
2018-11-27    5854.0    1  5804.0    1  SP1909
2018-11-27    5852.0    3  5806.0    4  SP1909
2018-11-27    5806.0    2  5802.0    1  SP1909
2018-11-27    5850.0    1  5804.0    1  SP1909
2018-11-27    5856.0    4  5806.0    1  SP1909
2018-11-27    5854.0    3  5814.0    1  SP1909
2018-11-27    5850.0    2  5814.0    1  SP1909
2018-11-27    5848.0    1  5816.0    1  SP1909
2018-11-27    5846.0    1  5816.0    2  SP1909
2018-11-27    5842.0    2  5816.0    2  SP1909
2018-11-27    5842.0    2  5818.0    1  SP1909
2018-11-27    5842.0    2  5816.0    2  SP1909
2018-11-27    5818.0    1  5814.0    1  SP1909
2018-11-27    5842.0    2  5818.0    2  SP1909
2018-11-27    5840.0    2  5820.0    1  SP1909
2018-11-27    5842.0    2  5818.0    2  SP1909
2018-11-27    5820.0    1  5814.0    1  SP1909
2018-11-27    5840.0    2  5814.0    1  SP1909
2018-11-27    5840.0    2  5814.0    4  SP1909
2018-11-27    5836.0    2  5814.0    4  SP1909
2018-11-27    5836.0    2  5816.0    4  SP1909
2018-11-27    5834.0    1  5816.0    4  SP1909
2018-11-27    5834.0    1  5816.0    4  SP1909
2018-11-27    5820.0    2  5816.0    6  SP1909
...              ...  ...     ...  ...     ...
2019-08-30    4560.0    1  4558.0   11  SP1909
2019-08-30    4560.0    1  4558.0    1  SP1909
2019-08-30    4560.0    1  4558.0    1  SP1909
2019-08-30    4560.0    3  4558.0    1  SP1909
2019-08-30    4560.0    3  4558.0    1  SP1909
2019-08-30    4562.0   12  4560.0    9  SP1909
2019-08-30    4562.0   12  4558.0    1  SP1909
2019-08-30    4556.0    7  4554.0    1  SP1909
2019-08-30    4562.0   13  4560.0    9  SP1909
2019-08-30    4562.0   12  4554.0    2  SP1909
2019-08-30    4562.0   12  4554.0    1  SP1909
2019-08-30    4562.0   12  4558.0   28  SP1909
2019-08-30    4562.0   12  4558.0   28  SP1909
2019-08-30    4562.0   12  4558.0   28  SP1909
2019-08-30    4562.0   12  4558.0   28  SP1909
2019-08-30    4562.0   14  4558.0   28  SP1909
2019-08-30    4562.0   14  4558.0   28  SP1909
2019-08-30    4562.0    4  4558.0   28  SP1909
2019-08-30    4562.0    4  4558.0   18  SP1909
2019-08-30    4562.0    4  4558.0   17  SP1909
2019-08-30    4562.0    4  4558.0   18  SP1909
2019-08-30    4562.0    4  4558.0   18  SP1909
2019-08-30    4562.0    4  4560.0    2  SP1909
2019-08-30    4562.0    4  4560.0    2  SP1909
2019-08-30    4562.0    2  4560.0    2  SP1909
2019-08-30    4562.0    2  4558.0   21  SP1909
2019-08-30    4562.0    2  4558.0   38  SP1909
2019-08-30    4562.0    2  4558.0   21  SP1909
2019-08-30    4562.0    2  4558.0   21  SP1909
2019-08-30    4562.0    2  4558.0   21  SP1909

[3214137 rows x 10 columns]

In [116]:
taq_df.to_csv("futures.csv")